port 6382
bind 0.0.0.0
requirepass <guardian_redis_pass>
dir /var/lib/redis-guardian
maxmemory 128mb
maxmemory-policy noeviction
appendonly yes
appendfsync everysec
save 3600 1
hz 20
activedefrag yes
loglevel notice
logfile /var/log/redis/redis-guardian.log
