port 6379
bind 0.0.0.0
requirepass <core_redis_pass>
dir /var/lib/redis-core
maxmemory 2gb
maxmemory-policy volatile-lru
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
save 900 1
save 300 10
save 60 10000
tcp-keepalive 300
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
loglevel notice
logfile /var/log/redis/redis-core.log
