node_id: node1
env: production
guardian_priority: 70
network:
  public_ip: 135.125.175.223
  wg_ip: 10.10.0.1
  wg_port: 51820
  guardian_port: 9200
  speed_mbps: 2000
hardware:
  cpu_cores: 6
  cpu_model: "Intel Core Haswell @ 3099 MHz"
  ram_gb: 11.4
  disks:
    - path: /
      size_gb: 98.3
      type: nvme
  provider: "OVH, Frankfurt"
components:
  - livekit
  - fail2ban
  - wireguard
  - teqlif-guardian
  - promtail
