services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: unless-stopped
    network_mode: "host" # Kendi kurulu Redis'ine erişmek için en kolay yol budur
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
