# /etc/wireguard/wg0.conf — node2 (Worker - 198.12.123.33)
# V1.4: 6-Node Full Mesh

[Interface]
Address = 10.10.0.3/24
ListenPort = 51820
PrivateKey = <NODE2_PRIVATE_KEY>

[Peer] # Node1 Edge 1 (135.125.175.223)
PublicKey = ZzPgXoo1KoYvP9rMUgh/nujfVCooolIi7YRCwfE2u3U=
AllowedIPs = 10.10.0.1/32
Endpoint = 135.125.175.223:51820
PersistentKeepalive = 25

[Peer] # Gateway (94.16.105.135)
PublicKey = /YGxAovtao4Iq2FsSuaIcPtjmcU/LEp6vrhpwH+UAwk=
AllowedIPs = 10.10.0.2/32
Endpoint = 94.16.105.135:51820
PersistentKeepalive = 25

[Peer] # Node3 (5.249.165.10)
PublicKey = c605VCB4ZMfelKJ5nFPFz9OY0kJ/uxx56kT6bVHkoHw=
AllowedIPs = 10.10.0.4/32
Endpoint = 5.249.165.10:51820
PersistentKeepalive = 25

[Peer] # Node5 Core (45.146.252.165)
PublicKey = ytMl1Xt3vw+GiMiehVV+C2ekM+qAum+tQS3K+suyfCU=
AllowedIPs = 10.10.0.5/32
Endpoint = 45.146.252.165:51820
PersistentKeepalive = 25

[Peer] # Node4 Edge 2 (51.75.74.124)
PublicKey = HFqnwG/xa9SziEwX4mqkRYhazpOb6hFVlx+B02UReDw=
AllowedIPs = 10.10.0.6/32
Endpoint = 51.75.74.124:51820
PersistentKeepalive = 25
