port 6380
bind 0.0.0.0
requirepass <orch_redis_pass>
dir /var/lib/redis-orch
maxmemory 256mb
maxmemory-policy noeviction
appendonly no
save ""
hz 20
activedefrag yes
active-defrag-threshold-lower 10
active-defrag-threshold-upper 30
loglevel notice
logfile /var/log/redis/redis-orch.log
replicaof 10.10.0.11 6380
masterauth <orch_redis_pass>
