vrrp_script chk_postgres {
    script "/usr/bin/pg_isready -h 127.0.0.1 -p 5432 -q"
    interval 2
    weight -20
}

vrrp_script chk_redis {
    script "/usr/bin/redis-cli -p 6379 -a <core_redis_pass> --no-auth-warning ping"
    interval 2
    weight -20
}

vrrp_sync_group VG_CORE {
    group { VI_PG VI_Redis }
    notify_master "/etc/keepalived/scripts/wg_vip_failover.sh MASTER"
    notify_backup "/etc/keepalived/scripts/wg_vip_failover.sh BACKUP"
}

vrrp_instance VI_PG {
    state BACKUP
    interface wg0
    virtual_router_id 51
    priority 100
    advert_int 1
    unicast_src_ip 10.10.0.7
    unicast_peer { 10.10.0.5 }
    authentication { auth_type PASS; auth_pass <keepalived_pass> }
    virtual_ipaddress { 10.10.0.10/32 }
    track_script { chk_postgres chk_redis }
}

vrrp_instance VI_Redis {
    state BACKUP
    interface wg0
    virtual_router_id 52
    priority 100
    advert_int 1
    unicast_src_ip 10.10.0.7
    unicast_peer { 10.10.0.5 }
    authentication { auth_type PASS; auth_pass <keepalived_pass> }
    virtual_ipaddress { 10.10.0.11/32 }
    track_script { chk_postgres chk_redis }
}
