[Interface]
Address    = 10.10.0.3/24
ListenPort = 51820
MTU        = 1420
PrivateKey = <privatekey>

# node1 (Core — Redis koordinasyonu)
[Peer]
PublicKey = <node1_pubkey>
AllowedIPs = 10.10.0.1/32
Endpoint = 193.70.46.74:51820
PersistentKeepalive = 25

# node2 (Monitoring — Prometheus scrape, Loki push)
[Peer]
PublicKey = <node2_pubkey>
AllowedIPs = 10.10.0.2/32
Endpoint = 135.125.223.43:51820
PersistentKeepalive = 25

# node4 (Streaming #2)
[Peer]
PublicKey = <node4_pubkey>
AllowedIPs = 10.10.0.4/32
Endpoint = 135.125.175.223:51820
PersistentKeepalive = 25

# node5 (Staging)
[Peer]
PublicKey = <node5_pubkey>
AllowedIPs = 10.10.0.5/32
Endpoint = 45.146.252.165:51821
PersistentKeepalive = 25

# node6 (AI Primary)
[Peer]
PublicKey = <node6_pubkey>
AllowedIPs = 10.10.0.6/32
Endpoint = 5.249.165.10:51820
PersistentKeepalive = 25

# Mac (tucibeyin — admin)
[Peer]
PublicKey = wEWDahzdObSI6p8DNthHSdBn6tlJDo+j96lBCeUi1To=
AllowedIPs = 10.10.0.7/32
