"""add shadowban and automod

Revision ID: 77d110fe1803
Revises: 46bc27c1940b
Create Date: 2026-03-31 08:14:43.803582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d110fe1803'
down_revision: Union[str, Sequence[str], None] = '46bc27c1940b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('is_hidden', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('direct_messages', sa.Column('flag_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_shadowbanned', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_shadowbanned')
    op.drop_column('direct_messages', 'flag_reason')
    op.drop_column('direct_messages', 'is_hidden')
    # ### end Alembic commands ###
