"""add phone to users

Revision ID: bbd66ab46108
Revises: k6l7m8n9o0p1
Create Date: 2026-04-08 16:55:20.723587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd66ab46108'
down_revision: Union[str, Sequence[str], None] = 'k6l7m8n9o0p1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'])
    op.create_index('ix_favorites_user_listing', 'favorites', ['user_id', 'listing_id'], unique=False)
    op.drop_index('ix_stream_likes_stream_created', table_name='stream_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stream_likes_stream_created', 'stream_likes', ['stream_id', 'created_at'], unique=False)
    op.drop_index('ix_favorites_user_listing', table_name='favorites')
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
