"""create_live_streams_table

Revision ID: dddf1a14c4eb
Revises: 4162603e4c1f
Create Date: 2026-03-13 16:41:55.625407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddf1a14c4eb'
down_revision: Union[str, Sequence[str], None] = '4162603e4c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('viewer_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_streams_id'), 'live_streams', ['id'], unique=False)
    op.create_index(op.f('ix_live_streams_room_name'), 'live_streams', ['room_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_streams_room_name'), table_name='live_streams')
    op.drop_index(op.f('ix_live_streams_id'), table_name='live_streams')
    op.drop_table('live_streams')
    # ### end Alembic commands ###
