port: 7880
bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  use_external_ip: true

turn:
  enabled: true
  domain: stream3.teqlif.com
  tls_port: 5349
  udp_port: 3478
  relay_range_start: 50000
  relay_range_end: 60000
  cert_file: /project/teqlif/config/ssl/stream3.teqlif.com-fullchain.pem
  key_file:  /project/teqlif/config/ssl/stream3.teqlif.com-privkey.pem

# Tüm streaming node'ları aynı Redis'e bağlanır — otomatik koordinasyon
redis:
  address: 10.10.0.1:6379
  db: 1
  password: <core_redis_pass>

keys:
  <livekit_api_key>: <livekit_api_secret>

logging:
  level: info
  json: true
