from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

class AnalyticsEventCreate(BaseModel):
    session_id: str = Field(..., description="Anonymous UUID generated by the client")
    event_type: str = Field(..., description="Type of event (e.g., page_view, sign_up, custom_action)")
    url: Optional[str] = None
    device_type: Optional[str] = None
    os: Optional[str] = None
    browser: Optional[str] = None
    event_metadata: Optional[Dict[str, Any]] = None
