from typing import Optional, Dict, Any, List, Literal
from pydantic import BaseModel, Field

class AnalyticsEventCreate(BaseModel):
    session_id: str = Field(..., description="Anonymous UUID generated by the client")
    event_type: str = Field(..., description="Type of event (e.g., page_view, sign_up, custom_action)")
    url: Optional[str] = None
    device_type: Optional[str] = None
    os: Optional[str] = None
    browser: Optional[str] = None
    event_metadata: Optional[Dict[str, Any]] = None


class FeedEventCreate(BaseModel):
    listing_id: str = Field(..., max_length=64)
    event_type: Literal["skip", "impression", "click"]
    dwell_time_ms: int = Field(default=0, ge=0)
    content_type: Literal["video", "photo"] = "video"
    slot_index: int = Field(default=0, ge=0)
    stream_category: str = Field(default="", max_length=64)
    listing_condition: str = Field(default="", max_length=20)


class FeedEventBatch(BaseModel):
    events: List[FeedEventCreate] = Field(..., max_length=500)


class SearchEventCreate(BaseModel):
    query: str = Field(..., min_length=1, max_length=500)
    category: str = Field(default="", max_length=64)
    result_count: int = Field(default=0, ge=0)
