[Interface]
Address    = 10.10.0.2/24
ListenPort = 51820
MTU        = 1420
PrivateKey = <privatekey>

# gateway2
[Peer]
PublicKey = <gateway2_pubkey>
AllowedIPs = 10.10.0.9/32
Endpoint = 185.205.194.232:51820
PersistentKeepalive = 25

# node1
[Peer]
PublicKey = <node1_pubkey>
AllowedIPs = 10.10.0.1/32
Endpoint = 135.125.175.223:51820
PersistentKeepalive = 25

# node2
[Peer]
PublicKey = <node2_pubkey>
AllowedIPs = 10.10.0.3/32
Endpoint = 198.12.123.33:51820
PersistentKeepalive = 25

# node3
[Peer]
PublicKey = <node3_pubkey>
AllowedIPs = 10.10.0.4/32
Endpoint = 5.249.165.10:51820
PersistentKeepalive = 25

# node4
[Peer]
PublicKey = <node4_pubkey>
AllowedIPs = 10.10.0.6/32
Endpoint = 51.75.74.124:51820
PersistentKeepalive = 25

# node5 — PRIMARY CORE
[Peer]
PublicKey = <node5_pubkey>
AllowedIPs = 10.10.0.5/32, 10.10.0.10/32, 10.10.0.11/32
Endpoint = <node5_public_ip>:51820
PersistentKeepalive = 25

# node6 — STANDBY CORE
[Peer]
PublicKey = <node6_pubkey>
AllowedIPs = 10.10.0.7/32
Endpoint = 185.205.194.173:51820
PersistentKeepalive = 25

# node7
[Peer]
PublicKey = <node7_pubkey>
AllowedIPs = 10.10.0.8/32
Endpoint = 82.39.86.94:51820
PersistentKeepalive = 25

# node8
[Peer]
PublicKey = <node8_pubkey>
AllowedIPs = 10.10.0.12/32
Endpoint = 96.62.250.101:51820
PersistentKeepalive = 25

# node9
[Peer]
PublicKey = <node9_pubkey>
AllowedIPs = 10.10.0.13/32
Endpoint = <node9_public_ip>:51820
PersistentKeepalive = 25

