server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://10.10.0.13:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      labels:
        job: journal
        node: node9
    relabel_configs:
      - source_labels: [__journal__systemd_unit]
        target_label: unit
      - source_labels: [__journal_priority_keyword]
        target_label: level

  - job_name: teqlif_file_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: teqlif
          node: node9
          __path__: /var/log/teqlif/**
