node_id: node9
env: production
guardian_priority: 30
network:
  public_ip: <node9_public_ip>
  wg_ip: 10.10.0.13
  wg_port: 51820
  guardian_port: 9200
  speed_mbps: 1000
hardware:
  cpu_cores: 8
  cpu_model: "Intel Xeon D-2123IT"
  ram_gb: 31
  disks:
    - path: /
      size_gb: 150
      type: hdd
    - path: /data
      size_gb: 3500
      type: hdd-raid1
  provider: "Hetzner"
components:
  - prometheus
  - alertmanager
  - grafana
  - loki
  - clickhouse
  - teqlif-pg-receivewal
  - fail2ban
  - wireguard
  - teqlif-guardian
  - promtail
