default_platform(:android)

platform :android do
  desc "Teqlif'i derle ve Internal Test'e taslak olarak gönder"
  lane :deploy_internal do
    
    # 1. Sürüm Kodunu Güvenli Şekilde Artır (Klasör karmaşasını çözen şaşmaz yol)
    pubspec_path = File.expand_path("../../pubspec.yaml", __dir__)
    pubspec_content = File.read(pubspec_path)
    pubspec_content.gsub!(/version: (\d+\.\d+\.\d+)\+(\d+)/) { |match| "version: #{$1}+#{$2.to_i + 1}" }
    File.write(pubspec_path, pubspec_content)
    UI.success("Versiyon başarıyla artırıldı!")

    # 2. Temizlik ve Derleme
    sh("cd .. && flutter clean && flutter pub get && flutter build appbundle")

    # 3. Yükleme
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      release_status: 'draft',
      skip_upload_metadata: false,
      skip_upload_images: false
    )
  end
end