node_id: node2
env: production
guardian_priority: 35
network:
  public_ip: 198.12.123.33
  wg_ip: 10.10.0.3
  wg_port: 51820
  guardian_port: 9200
  speed_mbps: 300
hardware:
  cpu_cores: 1
  cpu_model: "Intel Xeon E5-2670 v2 @ 2.50 GHz"
  ram_gb: 1.4
  disks:
    - path: /
      size_gb: 14.7
      type: hdd
  provider: "RackNerd, Buffalo NY"
components:
  - teqlif-ai-proxy
  - fail2ban
  - wireguard
  - teqlif-guardian
  - promtail
