node_id: node8
env: production
guardian_priority: 45
network:
  public_ip: 96.62.250.101
  wg_ip: 10.10.0.12
  wg_port: 51820
  guardian_port: 9200
  speed_mbps: 1000
hardware:
  cpu_cores: 2
  cpu_model: "Intel Xeon E5-2699 v4 @ 2.20 GHz"
  ram_gb: 2.9
  disks:
    - path: /
      size_gb: 10
      type: ssd
    - path: /mnt/data
      size_gb: 1000
      type: hdd
  provider: "Deluxhost, Amsterdam"
components:
  - minio
  - nginx
  - fail2ban
  - wireguard
  - teqlif-guardian
  - promtail
